import { Buffer } from 'buffer';
import type { DaveProject } from '../types';
import { useSevenStore } from '../store/useSevenStore';
import { fetchWithTimeout } from './network';

interface GitHubFile { path: string; mode: '100644'; type: 'blob'; sha: string; }

class GitHubProjectService {
  private config(): { token: string; owner: string; repo: string } {
    const config = useSevenStore.getState().config;
    const token = config.githubToken?.trim() || '';
    const [owner, repo] = (config.githubRepository || '').trim().split('/');
    if (!token || !owner || !repo) throw new Error('Configure a GitHub token and owner/repository in Autonomy Control.');
    return { token, owner, repo };
  }

  private async api(path: string, init: RequestInit = {}): Promise<any> {
    const { token } = this.config();
    const response = await fetchWithTimeout(`https://api.github.com${path}`, {
      ...init,
      headers: { Accept: 'application/vnd.github+json', Authorization: `Bearer ${token}`, 'X-GitHub-Api-Version': '2022-11-28', ...(init.headers || {}) },
    }, 30_000);
    const payload = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(`GitHub ${response.status}: ${payload?.message || 'request failed'}`);
    return payload;
  }

  async publishPullRequest(project: DaveProject): Promise<{ url: string; branch: string; commit: string }> {
    const { owner, repo } = this.config();
    const repository = await this.api(`/repos/${owner}/${repo}`);
    const base = repository.default_branch as string;
    const ref = await this.api(`/repos/${owner}/${repo}/git/ref/heads/${encodeURIComponent(base)}`);
    const baseCommit = ref.object.sha as string;
    const branch = `dave/${project.name.replace(/[^a-z0-9/_-]/gi, '-').slice(0, 50)}-${Date.now().toString(36)}`;
    await this.api(`/repos/${owner}/${repo}/git/refs`, { method: 'POST', body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: baseCommit }) });

    const files: GitHubFile[] = await Promise.all(Object.entries(project.files).map(async ([path, content]) => {
      const blob = await this.api(`/repos/${owner}/${repo}/git/blobs`, { method: 'POST', body: JSON.stringify({ content: Buffer.from(content).toString('base64'), encoding: 'base64' }) });
      return { path: `${project.name}/${path}`, mode: '100644', type: 'blob', sha: blob.sha };
    }));
    const baseData = await this.api(`/repos/${owner}/${repo}/git/commits/${baseCommit}`);
    const tree = await this.api(`/repos/${owner}/${repo}/git/trees`, { method: 'POST', body: JSON.stringify({ base_tree: baseData.tree.sha, tree: files }) });
    const commit = await this.api(`/repos/${owner}/${repo}/git/commits`, { method: 'POST', body: JSON.stringify({ message: `feat(dave): add ${project.name}`, tree: tree.sha, parents: [baseCommit] }) });
    await this.api(`/repos/${owner}/${repo}/git/refs/heads/${encodeURIComponent(branch)}`, { method: 'PATCH', body: JSON.stringify({ sha: commit.sha }) });
    const pull = await this.api(`/repos/${owner}/${repo}/pulls`, { method: 'POST', body: JSON.stringify({ title: `DAVE: ${project.name}`, head: branch, base, body: `Generated by SEVEN DAVE.\n\nObjective: ${project.prompt}\n\nReview and CI approval are required before merge.` }) });
    return { url: pull.html_url, branch, commit: commit.sha };
  }
}

export const githubProjectService = new GitHubProjectService();
