import { FONT } from './typography';
import type { Palette } from './theme';

export const researchStyles = (palette: Palette) => ({
  topNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: palette.bgElevated,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
  },
  backBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  backBtnText: {
    fontFamily: FONT.mono,
    color: palette.accent,
    fontSize: 12,
    fontWeight: '700',
  },
  titleWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  titleText: {
    fontFamily: FONT.mono,
    color: palette.text,
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 1,
  },
  placeholderRight: {
    width: 60,
  },
  scrollArea: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 40,
  },
  inputDeck: {
    backgroundColor: palette.bgElevated,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.borderStrong,
    padding: 12,
    marginBottom: 10,
  },
  labelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
  },
  deckLabel: {
    fontFamily: FONT.mono,
    color: palette.accent,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 1,
  },
  inputRow: {
    flexDirection: 'row',
    gap: 8,
  },
  textInput: {
    flex: 1,
    backgroundColor: palette.bgDeep,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 4,
    paddingHorizontal: 10,
    paddingVertical: 8,
    color: palette.text,
    fontFamily: FONT.mono,
    fontSize: 14,
  },
  compileBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: palette.accent,
    paddingHorizontal: 12,
    borderRadius: 4,
    gap: 5,
  },
  btnLoading: {
    opacity: 0.6,
  },
  compileText: {
    fontFamily: FONT.mono,
    color: palette.bgDeep,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  presetScroll: {
    marginTop: 10,
  },
  presetContainer: {
    gap: 6,
  },
  presetChip: {
    backgroundColor: palette.accentSoft,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 8,
    paddingVertical: 8,
    minHeight: 44,
    justifyContent: 'center',
    borderRadius: 3,
  },
  presetText: {
    fontFamily: FONT.mono,
    color: palette.textDim,
    fontSize: 12,
  },
  docCard: {
    backgroundColor: palette.bgElevated,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 14,
    marginTop: 10,
  },
  docCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  docHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  docTitleText: {
    fontFamily: FONT.mono,
    color: palette.accent,
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  docMetaText: {
    fontFamily: FONT.mono,
    color: palette.textFaint,
    fontSize: 12,
    marginTop: 2,
  },
  pdfReadyBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: palette.accentSoft,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 3,
    borderWidth: 1,
    borderColor: palette.success,
  },
  pdfReadyText: {
    fontFamily: FONT.mono,
    color: palette.success,
    fontSize: 12,
    fontWeight: '800',
  },
  summaryBox: {
    backgroundColor: palette.accentSoft,
    borderLeftWidth: 3,
    borderLeftColor: palette.accent,
    padding: 10,
    borderRadius: 4,
    marginBottom: 12,
  },
  summaryLabel: {
    fontFamily: FONT.mono,
    color: palette.accent,
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 4,
  },
  summaryBody: {
    fontFamily: FONT.mono,
    color: palette.text,
    fontSize: 14,
    lineHeight: 15,
  },
  sectionsList: {
    gap: 10,
    marginBottom: 14,
  },
  sectionItem: {
    backgroundColor: palette.bgDeep,
    padding: 10,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: palette.border,
  },
  sectionHeading: {
    fontFamily: FONT.mono,
    color: palette.text,
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 4,
  },
  sectionBody: {
    fontFamily: FONT.mono,
    color: palette.textDim,
    fontSize: 13,
    lineHeight: 14,
  },
  sourcesBox: {
    backgroundColor: palette.bgDeep,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 4,
    padding: 10,
    gap: 6,
    marginBottom: 14,
  },
  sourceLink: {
    color: palette.info,
    fontFamily: FONT.ui,
    fontSize: 13,
    lineHeight: 18,
    textDecorationLine: 'underline',
  },
  docActions: {
    flexDirection: 'row',
    gap: 10,
  },
  shareBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.accent,
    paddingVertical: 12,
    minHeight: 48,
    borderRadius: 4,
    gap: 6,
  },
  shareBtnText: {
    fontFamily: FONT.mono,
    color: palette.bgDeep,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  openBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.accentSoft,
    borderWidth: 1,
    borderColor: palette.accent,
    paddingVertical: 12,
    minHeight: 48,
    borderRadius: 4,
    gap: 6,
  },
  openBtnText: {
    fontFamily: FONT.mono,
    color: palette.accent,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
} as const);
